version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_composer_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 30
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user
